# Generated by Django 4.0.3 on 2022-05-07 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_jobs_saved_by'),
        ('users', '0002_user_created_at_user_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='saved_jobs',
            field=models.ManyToManyField(related_name='saved_jobs', to='jobs.jobs'),
        ),
    ]
