# Generated by Django 4.0.3 on 2022-05-07 10:16

from django.db import migrations
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0007_jobs_applied_by_alter_jobs_saved_by'),
        ('users', '0004_remove_user_saved_jobs_user_saved_jobs'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='applied_jobs',
            field=djongo.models.fields.ArrayReferenceField(blank=True, null=True, on_delete=djongo.models.fields.ArrayReferenceField._on_delete, related_name='applied_jobs', to='jobs.jobs'),
        ),
        migrations.AlterField(
            model_name='user',
            name='saved_jobs',
            field=djongo.models.fields.ArrayReferenceField(blank=True, null=True, on_delete=djongo.models.fields.ArrayReferenceField._on_delete, related_name='saved_jobs', to='jobs.jobs'),
        ),
    ]
