# Generated by Django 4.0.3 on 2022-04-01 17:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255, unique=True)),
                ('company_description', models.TextField(blank=True, null=True)),
                ('company_logo', models.TextField(blank=True, null=True)),
                ('company_website', models.TextField(blank=True, null=True)),
                ('company_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('company_phone', models.CharField(blank=True, max_length=255, null=True)),
                ('company_address', models.TextField(blank=True, null=True)),
                ('company_city', models.CharField(blank=True, max_length=255, null=True)),
                ('company_state', models.CharField(blank=True, max_length=255, null=True)),
                ('job_title', models.CharField(blank=True, max_length=255, null=True)),
                ('job_description', models.TextField(blank=True, null=True)),
                ('job_requirements', models.TextField(blank=True, null=True)),
                ('job_salary', models.CharField(blank=True, max_length=255, null=True)),
                ('job_location', models.CharField(blank=True, max_length=255, null=True)),
                ('job_type', models.CharField(blank=True, max_length=255, null=True)),
                ('job_category', models.CharField(blank=True, max_length=255, null=True)),
                ('job_experience', models.CharField(blank=True, max_length=255, null=True)),
                ('job_education', models.CharField(blank=True, max_length=255, null=True)),
                ('job_skills', models.TextField(blank=True, null=True)),
                ('job_created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('job_updated_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
