# Generated by Django 4.0.3 on 2022-04-21 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_jobs_job_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='job_min_qualifications',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobs',
            name='job_pref_qualifications',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='job_experience',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='job_location',
            field=models.TextField(blank=True, null=True),
        ),
    ]
