# Generated by Django 4.0.3 on 2022-04-21 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_jobs_job_min_qualifications_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='company_address',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='company_city',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='company_description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='company_email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='company_logo',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='company_phone',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='company_state',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='company_website',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='job_category',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='job_description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='job_education',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='job_experience',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='job_location',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='job_min_qualifications',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='job_pref_qualifications',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='job_requirements',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='job_salary',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='job_skills',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='job_start_date',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='job_title',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='job_type',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
