# Generated by Django 4.0.3 on 2022-05-07 03:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jobs', '0004_alter_jobs_company_address_alter_jobs_company_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='saved_by',
            field=models.ManyToManyField(related_name='saved_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
