# Generated by Django 4.0.3 on 2022-05-07 09:44

from django.conf import settings
from django.db import migrations
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jobs', '0005_jobs_saved_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobs',
            name='saved_by',
        ),
        migrations.AddField(
            model_name='jobs',
            name='saved_by',
            field=djongo.models.fields.ArrayReferenceField(blank=True, null=True, on_delete=djongo.models.fields.ArrayReferenceField._on_delete, to=settings.AUTH_USER_MODEL),
        ),
    ]
