# Generated by Django 4.0.3 on 2022-05-07 10:16

from django.conf import settings
from django.db import migrations
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jobs', '0006_remove_jobs_saved_by_jobs_saved_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='applied_by',
            field=djongo.models.fields.ArrayReferenceField(blank=True, null=True, on_delete=djongo.models.fields.ArrayReferenceField._on_delete, related_name='applied_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='saved_by',
            field=djongo.models.fields.ArrayReferenceField(blank=True, null=True, on_delete=djongo.models.fields.ArrayReferenceField._on_delete, related_name='saved_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
